#!/usr/bin/php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

define('__ROOT__', __DIR__);
// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = include 'config/console.php';
$application = new yii\console\Application($config);
ob_start();
$application->run($config);
$msg = ob_get_clean();
if (isset($_SERVER['OS']) && false !== strpos(strtolower($_SERVER['OS']), 'windows') && strtolower(\Yii::$app->db->charset) == 'utf8') {
    $msg = iconv('UTF-8', 'GBK', $msg);
}
echo $msg;
