#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$composerAutoload = [
    __DIR__ . '/../vendor/autoload.php', // in yii2-dev repo
    __DIR__ . '/../../autoload.php', // installed as a composer binary
];
$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        $vendorPath = dirname($autoload);
        break;
    }
}


require(__DIR__ . '/../yii2/Yii.php');
$config = include __DIR__ . '/config/console.php';
$application = new yii\console\Application($config);
if (isset($vendorPath)) {
    $application->setVendorPath($vendorPath);
}
ob_start();
$application->run($config);
$msg = ob_get_clean();
if (isset($_SERVER['OS']) && false !== strpos(strtolower($_SERVER['OS']), 'windows') && strtolower(\Yii::$app->db->charset) == 'utf8') {
    $msg = iconv('UTF-8', 'GBK', $msg);
}
echo $msg;
